name: jq

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  jq:
    runs-on: ubuntu-latest
   
    steps:
        - name: set output
          id: set
          run: |
             echo ::set-output name=link::`curl -s https://api.github.com/repos/MichaelGrafnetter/DSInternals/releases/latest`
        - name: use output
          run: |
            echo ::set-output name=file::$(echo ${{ steps.set.outputs.link}} | jq .assets[0].name)
        - name: echo
          run: |
            echo $file
            echo ${{ steps.set.outputs.file}}
          env:
            link: ${{ steps.set.outputs.link}}

      
