name: jq

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  jq:
    runs-on: ubuntu-latest
   
    steps:
        - name: request github api
          id: api
          run: |
             echo "::set-output name=filename::$(curl -s https://api.github.com/repos/MichaelGrafnetter/DSInternals/releases/latest | jq -c .)"
        - name: echo
          run: |
            test=`echo "${{ steps.api.outputs.filename}}" | jq .assets[0].name | sed 's/\"//g'`
            echo $test
      
