name: jq

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  jq:
    runs-on: ubuntu-latest
   
    steps:
        - name: set output
          id: set
          run: |
             echo ::set-output name=json::`curl -s https://api.github.com/repos/MichaelGrafnetter/DSInternals/releases/latest`
        - name: use output
          run: |
            echo $json | jq .assets[0].browser_download_url
            echo $json | jq .assets[0].tag_name

      
