name: hardening

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - id: set-matrix
      run: |
        hardening="\"repo\":\"0x6d69636b\/windows_hardening\",\"content-type\":\"application\/zip\",\"file\":\"v.0.7.0.zip  | sed 's\/\\\"\/\/g'\",\"tag\":\"curl -s https:\/\/api.github.com\/repos\/0x6d69636b\/windows_hardening\/releases\/latest | jq .tag_name  | sed 's\/\\\"\/\/g'\""
        str="{\"include\":[{$hardening}]}"
        echo "::set-output name=matrix::$str"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
    - name: checkout current
      uses: actions/checkout@v2
        
    - name: request github api
      id: api
      run: |
            echo ::set-output name=tagname::`${{ matrix.tag }}`
    - name: echo
      run: |
          echo ${{ steps.api.outputs.tagname}}
   
    - name: download release
      id: get_release
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "${{ matrix.repo }}"
        latest: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: create custom release
      uses: actions/create-release@v1
      id: create-new-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.api.outputs.tagname}}
        release_name: v.0.7.0.zip
      
    - name: upload release   
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./windows_hardening-v.0.7.0.zip
        asset_name: v.0.7.0.zip
        asset_content_type: ${{ matrix.content-type }}
    
