name: hardening

on:
  schedule:
    - cron:  '*/15 * * * *'
            
permissions: write-all

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout current
      uses: actions/checkout@v2
        
    - name: request github api
      id: api
      run: |
          echo ::set-output name=tagname::`curl -s https://api.github.com/repos/0x6d69636b/windows_hardening/releases/latest | jq .tag_name  | sed 's/\"//g'`
    - name: echo
      run: |
          echo ${{ steps.api.outputs.tagname}}
            
    - name: download zipBall
      id: get_release
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "0x6d69636b/windows_hardening"
        latest: true
        zipBall: true
        fileName: "*"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: create custom release
      uses: actions/create-release@v1
      id: create-new-release
      with:
        tag_name: ${{ steps.api.outputs.tagname}}
        release_name: ${{ steps.api.outputs.tagname}}.zip
        draft: false
        prerelease: false
        body: releases_[hardening].yml - ${{ steps.api.outputs.tagname }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: upload release   
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./windows_hardening-v.0.7.0.zip
        asset_name: ${{ steps.api.outputs.tagname}}.zip
        asset_content_type: application/octet-stream
    
