name: releases

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - id: set-matrix
      run: |
        str="{\"include\": [{\"run\": \"run1\"}, {\"run\": \"run2\"}]"
        echo "::set-output name=matrix::$str"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
    - name: checkout current
      uses: actions/checkout@v2
        
    - name: create a subdirectory
      run: |
          mkdir test

    - name: request github api
      id: api
      run: |
            echo ::set-output name=filename::`${{ matrix.filename_cmd }}`
            echo ::set-output name=tagname::`${{ matrix.tag_cmd }}`
    - name: echo
      run: |
          echo ${{ steps.api.outputs.filename}}
          echo ${{ steps.api.outputs.tagname}}

    - name: download release
      id: get_release
      uses: dsaltares/fetch-gh-release-asset@master
      with:
          repo: "${{ matrix.repo }}"
          version: "latest"
          file: ${{ steps.api.outputs.filename}}
          target: "test/${{ steps.api.outputs.filename}}"
          token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
          echo ${{ steps.get_release.outputs.version }}
          echo ${{ steps.get_release.outputs.name }}
          echo ${{ steps.get_release.outputs.body }}
          
    - name: create custom release
      uses: actions/create-release@v1
      id: create-new-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.api.outputs.tagname}}
        release_name: ${{ steps.api.outputs.filename}}
      
    - name: upload release   
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./test/${{ steps.api.outputs.filename}}
        asset_name: ${{ steps.api.outputs.filename}}
        asset_content_type: application/zip 
    
