name: releases

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - id: set-matrix
      run: |
        repo1="\"repo\":\"MichaelGrafnetter\/DSInternals\",\"content-type\":\"application\/zip\",\"cmd1\":\"curl -s https:\/\/api.github.com\/repos\/MichaelGrafnetter\/DSInternals\/releases\/latest | jq .assets[0].name  | sed 's\/\\\"\/\/g'\",\"cmd2\":\"curl -s https:\/\/api.github.com\/repos\/MichaelGrafnetter\/DSInternals\/releases\/latest | jq .tag_name  | sed 's\/\\\"\/\/g'\""
        repo2="\"repo\":\"SnaffCon\/Snaffler\",\"content-type\":\"application\/zip\",\"cmd1\":\"curl -s https:\/\/api.github.com\/repos\/SnaffCon\/Snaffler\/releases\/latest | jq .assets[0].name  | sed 's\/\\\"\/\/g'\",\"cmd2\":\"curl -s https:\/\/api.github.com\/repos\/SnaffCon\/Snaffler\/releases\/latest | jq .tag_name  | sed 's\/\\\"\/\/g'\""
        repo3_1="\"repo\":\"wagga40\/Zircolite\",\"content-type\":\"application\/octet-stream\",\"cmd1\":\"curl -s https:\/\/api.github.com\/repos\/wagga40\/Zircolite\/releases\/latest | jq .assets[2].name  | sed 's\/\\\"\/\/g'\",\"cmd2\":\"curl -s https:\/\/api.github.com\/repos\/wagga40\/Zircolite\/releases\/latest | jq .tag_name  | sed 's\/\\\"\/\/g'\""
        str="{\"include\":[{$repo1},{$repo2}, {$repo3_1}]}"
        echo "::set-output name=matrix::$str"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
    - name: checkout current
      uses: actions/checkout@v2
        
    - name: create a subdirectory
      run: |
          mkdir test

    - name: request github api
      id: api
      run: |
            echo ::set-output name=filename::`${{ matrix.cmd1 }}`
            echo ::set-output name=tagname::`${{ matrix.cmd2 }}`
    - name: echo
      run: |
          echo ${{ steps.api.outputs.filename}}
          echo ${{ steps.api.outputs.tagname}}

    - name: download release
      id: get_release
      uses: dsaltares/fetch-gh-release-asset@master
      with:
          repo: "${{ matrix.repo }}"
          version: "latest"
          file: ${{ steps.api.outputs.filename}}
          target: "test/${{ steps.api.outputs.filename}}"
          token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
          echo ${{ steps.get_release.outputs.version }}
          echo ${{ steps.get_release.outputs.name }}
          echo ${{ steps.get_release.outputs.body }}
          
    - name: create custom release
      uses: actions/create-release@v1
      id: create-new-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.api.outputs.tagname}}
        release_name: ${{ steps.api.outputs.filename}}
      
    - name: upload release   
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./test/${{ steps.api.outputs.filename}}
        asset_name: ${{ steps.api.outputs.filename}}
        asset_content_type: ${{ matrix.content-type }}
    
