name: pick

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  pick:
    runs-on: ubuntu-latest
   
    steps:
      - name: Download artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "MichaelGrafnetter/DSInternals"
          version: "latest"
          file: "DSInternals_v4.7.zip"
          target: "test/DSInternals_v4.7.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: DSInternals_v4.7.zip
          path: test/DSInternals_v4.7.zip
